export enum ErrorCode {
  // Domain Product errors
  INVALID_PRODUCT_ID = "INVALID_PRODUCT_ID",
  PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND",
  INSUFFICIENT_STOCK = "INSUFFICIENT_STOCK",
  NEGATIVE_PRICE = "NEGATIVE_PRICE",
  INVALID_NAME = "INVALID_NAME",
  INVALID_SKU = "INVALID_SKU",
  NEGATIVE_STOCK = "NEGATIVE_STOCK",

  // Domain Customer errors
  CUSTOMER_NOT_FOUND = "CUSTOMER_NOT_FOUND",

  // Domain Order errors
  ORDER_NOT_FOUND = "ORDER_NOT_FOUND",

  // Application errors
  VALIDATION_ERROR = "VALIDATION_ERROR",
  USE_CASE_ERROR = "USE_CASE_ERROR",

  // Infrastructure errors
  DATABASE_ERROR = "DATABASE_ERROR",
  NETWORK_ERROR = "NETWORK_ERROR",
  FILE_SYSTEM_ERROR = "FILE_SYSTEM_ERROR",
  CONFIG_ERROR = "CONFIG_ERROR",
  AUTH_ERROR = "AUTH_ERROR",
}
